### ISSUE TITLE
examples/imageviewer: DrawText does not draw to a draw.Image

### ISSUE THREAD

**Issue by peterhellberg** [faiface/gui#3]
The `DrawText` function in `examples/imageviewer/util.go` creates a new image with the given text, it does not draw it on an image like the other `Draw*` functions.

https://github.com/faiface/gui/blob/4324b480c2170ac435ee85988d0260e5f38259b3/examples/imageviewer/util.go#L66-L82

**Comment by faiface** [comment]
Right! I changed it to `MakeTextImage` with [this commit](https://github.com/faiface/gui/commit/de5d2f5c78da7f8a578ecc25f8e8b1fa90f20264). Is that okay?

**Comment by peterhellberg** [comment]
That sounds good 👍
