### ISSUE TITLE
Maybe change Event to be an interface instead of struct?

### ISSUE THREAD

**Issue by peterhellberg** [faiface/gui#4]
I'm thinking something along these lines:

```go
type Event interface {
	Name() string
	Args() interface{}
}
```

This would look like this when in use:

```go
package main

import (
	"image"
	"image/draw"

	"github.com/peterhellberg/gfx"
	"github.com/peterhellberg/gui"
)

func main() {
	gui.Run(loop)
}

func loop() {
	win, err := gui.New(gui.Title("gui-xor"), gui.Size(512, 512))
	if err != nil {
		return
	}

	win.Draw() <- func(dst draw.Image) image.Rectangle {
		r := dst.Bounds()

		gfx.EachPixel(r, func(x, y int) {
			c := uint8(x ^ y)

			dst.Set(x, y, gfx.ColorNRGBA(c, c%192, c, 255))
		})

		return r
	}

	for event := range win.Events() {
		switch event.Name() {
		case gui.EventClose, gui.EventKeyboardUp:
			close(win.Draw())
		default:
			gfx.Log("Event: %+v", event)
		}
	}
}
```

<img width="256" alt="gui-xor" src="https://user-images.githubusercontent.com/565124/57329314-d007cc00-7113-11e9-892b-e4c75401004f.png">

I will experiment a bit more, but so far I've reduced the code in this project to a [single file](https://raw.githubusercontent.com/peterhellberg/gui/73abe895340b23ea67bf38039b0f5c5d534bb445/gui.go) (in order to help with the experimentation)

**Comment by faiface** [comment]
Thanks a lot for thinking about this!

There is one more benefit to the original string events that you don't cover here and that's this:

```go
switch {
case event.Matches("kb/down/left"):
    // ...
case event.Matches("kb/down/right"):
    // ...
}
```

Matching directly on the values of the event, like specific keys. We don't necessarily need to address it, but it would be nice.

**Comment by peterhellberg** [comment]
Switching on the args can be done in a second switch for example if you want to do something when the letter `q` is typed on the keyboard:

```go
switch event.Name() {
case gui.EventKeyboardChar:
	switch event.Args().(int32) {
	case 'q':
		win.Close()
	}
}
```

**Comment by faiface** [comment]
Yeah, I know, but that requires another switch, you know. It's quite nicer to have to all in a single switch.

**Comment by faiface** [comment]
Btw, what do you think about something as straightforward as this?

```go
type Event interface{}

type EventResize struct {
    Bounds image.Rectangle
}

type EventKbDown struct {
    Key string
}

type EventMoMove struct {
    Point image.Point
}

// more event types
```

**Comment by faiface** [comment]
And perhaps adding a `String()` method to the `Event` interface, so that events are nicely printable for debugging.

**Comment by peterhellberg** [comment]
Then you would be back to using a concrete type for each event instead of an interface that could be implemented by someone else.

**Comment by faiface** [comment]
Yeah, but an event is just data, right? I'm not sure a single type of event needs multiple implementations. And adding more types of events would be easy, just add a new event type.

**Comment by faiface** [comment]
Perhaps I'm missing some of your points :D

**Comment by peterhellberg** [comment]
I'll continue experimenting to see what I come up with :)

Thank you for creating this project, it is very close to exactly what I've wanted when displaying my experiments with github.com/peterhellberg/gfx

**Comment by faiface** [comment]
Thanks! I appreciate that a lot. I also appreciate your feedback and suggestions.

**Comment by faiface** [comment]
Have you figured something out? I think I'll try the structs, see how it goes.

**Comment by peterhellberg** [comment]
Not much, other than deciding to rename the Args field to Data :)

```go
// Event includes its name and data.
type Event interface {
	Name() string
	Data() interface{}
}
```

I've started to think a bit about how/if it would make sense to being able to trigger custom events (on a timer, when receiving data over the network, etc.) Will probably not have that much time tonight though.

**Comment by faiface** [comment]
The thing is, that with concurrent GUI, you can solve that kind of thing simply with channels. You make a long running thing send a value over a channel and you select on that channel alonside selecting on the events channel.

**Comment by faiface** [comment]
I decided to give concrete event types a try.

**Comment by peterhellberg** [comment]
Ok :)
